import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium, devices } from 'playwright';

const out = process.argv[2] || './tmp';
await mkdir(out, { recursive: true });
const browser = await chromium.launch(process.env.PW_CHROMIUM ? { executablePath: process.env.PW_CHROMIUM } : {});
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(process.env.BASE_URL || 'http://127.0.0.1:4173/', { waitUntil: 'networkidle' });
  await page.getByRole('button', { name: '再生', exact: true }).waitFor();
  assert.equal(await page.locator('#year').textContent(), '0');
  await page.screenshot({ path: `${out}/river-initial.png`, fullPage: true });
  await page.locator('#advance').click();
  await page.waitForFunction(() => document.querySelector('#year').textContent === '100');
  await page.getByRole('button', { name: '再生', exact: true }).waitFor();
  await page.locator('#advance').click();
  await page.waitForFunction(() => document.querySelector('#year').textContent === '200');
  assert.ok(Number.parseInt(await page.locator('#oxbows').textContent()) > 0);
  const shape200 = await page.locator('#sinuosity').textContent();
  await page.screenshot({ path: `${out}/river-desktop.png`, fullPage: true });
  await page.locator('#save').click();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem('river-observatory-v1')));
  assert.equal(stored.state.year, 200);
  await page.locator('#timeline').fill('0');
  assert.equal(await page.locator('#year').textContent(), '0');
  assert.equal(await page.locator('#flow').isDisabled(), true);
  assert.equal(await page.locator('#event').isHidden(), true);
  await page.locator('#latest').click();
  assert.equal(await page.locator('#sinuosity').textContent(), shape200);
  await page.locator('#timeline').fill('0');
  await page.locator('#speed').selectOption('80');
  await page.locator('#play').click();
  await page.waitForFunction(() => Number(document.querySelector('#year').textContent.replaceAll(',', '')) > 30);
  await page.locator('#play').click();
  await page.locator('#latest').click();
  await page.locator('#flood').click();
  assert.match(await page.locator('#flood').textContent(), /増水中/);
  await page.locator('#flow').fill('1.5');
  assert.match(await page.locator('#flow-value').textContent(), /1.50/);
  await page.locator('#erosion').fill('1.8');
  assert.match(await page.locator('#erosion-value').textContent(), /1.80/);
  for (const id of ['trails', 'flow-layer', 'terrain']) { await page.locator(`#${id}`).uncheck(); await page.locator(`#${id}`).check(); }
  await page.locator('#reset').click();
  assert.equal(await page.locator('#year').textContent(), '0');
  await page.locator('#load').click();
  assert.equal(await page.locator('#year').textContent(), '200');
  assert.equal(await page.locator('#sinuosity').textContent(), shape200);
  await page.locator('#about').click();
  await page.locator('#about-dialog').waitFor({ state: 'visible' });
  await page.keyboard.press('Escape');
  await page.locator('#about-dialog').waitFor({ state: 'hidden' });
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#capture').click();
  const download = await downloadPromise;
  assert.match(download.suggestedFilename(), /river-200years.png/);
  await download.saveAs(`${out}/river-export.png`);
  await page.evaluate(() => localStorage.setItem('river-observatory-v1', 'broken'));
  await page.locator('#load').click();
  assert.equal(await page.locator('#year').textContent(), '200');
  assert.match(await page.locator('#notification').textContent(), /読み込めません/);
  await page.locator('#preset').selectOption('sand');
  assert.equal(await page.locator('#year').textContent(), '0');
  assert.match(await page.locator('#field-title').textContent(), /砂地/);
  // A completed save has no earlier timeline; replay must still start a new run.
  await page.evaluate(saved => {
    saved.state.year = 1200;
    localStorage.setItem('river-observatory-v1', JSON.stringify(saved));
  }, stored);
  await page.locator('#load').click();
  assert.equal(await page.locator('#year').textContent(), '1,200');
  await page.getByRole('button', { name: 'はじめから再生' }).click();
  await page.waitForFunction(() => Number(document.querySelector('#year').textContent.replaceAll(',', '')) < 1200);
  await page.getByRole('button', { name: '一時停止', exact: true }).click();
  const mobile = await browser.newContext({ ...devices['iPhone 13'], reducedMotion: 'reduce' });
  const phone = await mobile.newPage(); phone.on('pageerror', e => errors.push(e.message));
  await phone.goto(process.env.BASE_URL || 'http://127.0.0.1:4173/', { waitUntil: 'networkidle' });
  await phone.locator('#advance').click();
  await phone.waitForFunction(() => document.querySelector('#year').textContent === '100');
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await phone.screenshot({ path: `${out}/river-mobile.png`, fullPage: true });
  await phone.setViewportSize({ width: 320, height: 700 });
  assert.equal(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await phone.locator('#preset').selectOption('forest');
  assert.match(await phone.locator('#field-title').textContent(), /森/);
  await phone.getByRole('link', { name: /砂の実験室/ }).click();
  await phone.getByRole('button', { name: /箱庭をはじめる/ }).waitFor();
  assert.equal(errors.length, 0, JSON.stringify(errors));
  console.log(JSON.stringify({ passed: true, desktop: '1440×1000', mobile: 'iPhone 13', tested: ['geometric cutoffs', 'pause', 'replay', 'seek', 'latest', 'parameters', 'flood', 'layers', 'presets', 'save/restore', 'invalid save', 'PNG', 'dialog', 'mobile overflow', 'legacy route'], errors }, null, 2));
} finally { await browser.close(); }
